### ISSUE TITLE
Node client fails trying to use the basic example code you provide

### ISSUE THREAD

**Issue by grempe** [stampery/node#4]
I have been trying (in good faith) to try to get your API code to work.  You have resolved some issues (#1, #2, #3), but it still fails. You really need tests for your code. Here is the latest failure example.

Also, you really should not close issues until it is confirmed with the submitter that the issue is actually resolved.

```
~/src/stampery-test$ node index.js
/Users/glenn/src/stampery-test/node_modules/stampery/index.js:77
      this.clientId = this._hash('md5', this.clientSecret).substring(0, 15);
                           ^

TypeError: this._hash is not a function
    at new Stampery (/Users/glenn/src/stampery-test/node_modules/stampery/index.js:77:28)
    at Object.<anonymous> (/Users/glenn/src/stampery-test/index.js:6:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

Here is the sample code I am trying to run (copied from the README of this project):

```
Stampery = require('stampery');

stampery = new Stampery('REDACTED')

stampery.on('proof', function(hash, proof) {
  console.log("Received proof for " + hash, proof);
  valid = stampery.prove(hash, proof);
  console.log('Proof validity:', valid);
});

stampery.on('ready', function() {
  stampery.receiveMissedProofs();
  stampery.hash('The piano has been drinking', function(hash) {
    stampery.stamp(hash);
  });
});

```

My package.json looks like:

```
{
  "name": "stampery-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "node index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "stampery": "^3.1.2"
  }
}
```

**Comment by grempe** [comment]
https://twitter.com/grempe/status/755274821617852416

**Comment by grempe** [comment]
@aesedepece I tested again with your newly released v3.2.0, blew away node_modules dir first, same issue still exists.

```
~/src/stampery-test$ node index.js
/Users/glenn/src/stampery-test/node_modules/stampery/index.js:81
      this.clientId = this._hash('md5', this.clientSecret).substring(0, 15);
                           ^

TypeError: this._hash is not a function
    at new Stampery (/Users/glenn/src/stampery-test/node_modules/stampery/index.js:81:28)
    at Object.<anonymous> (/Users/glenn/src/stampery-test/index.js:6:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by bachvtuan** [comment]
Me neither, my node version is v4.4.3.
My code just like example but I changed secret token then I get this error.

```
/home/geek/Desktop/kp/test/node_modules/stampery/index.js:3
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };
                                                           ^

TypeError: Cannot read property 'apply' of undefined
    at Stampery._connectRabbit (/home/geek/Desktop/kp/test/node_modules/stampery/index.js:3:60)
    at new Stampery (/home/geek/Desktop/kp/test/node_modules/stampery/index.js:67:12)
    at Object.<anonymous> (/home/geek/Desktop/kp/test/timestamp.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

```

**Comment by aesedepece** [comment]
@bachvtuan @grempe The Stampery nodejs wrapper is intended to be used with Node 5.x or greater, as said in the `engines` section of `package.json`. Sorry for the inconveniences :crying_cat_face:

**Comment by bachvtuan** [comment]
Hi. I just downloaded the latest nodejs version is v6.4.0. A different error was shown up.

```
module.js:583
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/geek/Desktop/kp/test/node_modules/stampery/index.js:12:10)
    at Object.<anonymous> (/home/geek/Desktop/kp/test/node_modules/stampery/index.js:533:4)
    at Module._compile (module.js:556:32)

```

**Comment by aesedepece** [comment]
This issue should no longer be present with latest `6.0.0` release, which is a complete rewrite and supports nodejs `>=4.0.0`.
Please confirm. Thanks in advance.

**Comment by grempe** [comment]
Nope. Could not get new code to run a successful test. Here is the new test code and the error. It fails when trying to prove the result. Stampery `v6.0.1`. I used the sample code from your README and just modified it to be nested and wait 10 seconds longer than the predicted amount for `eth`. It always fails on `stampery.prove`. Perhaps the fact that there are no tests that can be run for this code is showing?

```
$ node --version
v7.4.0
```

```
const Stampery = require('stampery')
var stampery = new Stampery('API_KEY')

var sleep = function (ms) {
  return new Promise(resolve => setTimeout(resolve, ms))
}

var h = stampery.hash('the piano has been drinking ' + Math.random())

stampery.stamp(h, function (err, stamp) {
  if (err) {
    return console.error(err)
  }

  console.log('RESPONSE stamp')
  console.log(stamp)

  // sleep for 10 seconds longer than predicted necessary
  sleep(stamp.receipts.eth * 1000 + 10000).then(() => {
    stampery.getById(stamp.id, function (err, res) {
      if (err) {
        console.error('FAILED')
        return console.error(err)
      }

      if (res) {
        console.log('RESPONSE getById')
        console.log(res)

        console.log('PROVE IT')
        return console.log('Valid: ', stampery.prove(res.receipts))
      }
    })
  })
})
```

Error:

```
$ node index2.js
RESPONSE stamp
{ time: '2017-01-23 21:34:06.655025',
  hash: '494C9E5ED0FD350EBBE7DEC3AA8F9377D4E478ABEAB702ACBDF6A562F1755ACE',
  receipts: { btc: 401, eth: 56 },
  token: '1b997d902a3792e',
  id: '588676cecbef130004fbf400' }
RESPONSE getById
{ time: '2017-01-23 21:34:06.655000',
  hash: '494C9E5ED0FD350EBBE7DEC3AA8F9377D4E478ABEAB702ACBDF6A562F1755ACE',
  receipts:
   { btc: 334,
     eth:
      { proof: [],
        targetHash: '494C9E5ED0FD350EBBE7DEC3AA8F9377D4E478ABEAB702ACBDF6A562F1755ACE',
        type: 'BTA-SHA256',
        '@context': 'https://w3id.org/chainpoint/v2',
        anchors: [Object],
        merkleRoot: '494C9E5ED0FD350EBBE7DEC3AA8F9377D4E478ABEAB702ACBDF6A562F1755ACE' } },
  token: '1b997d902a3792e',
  id: '588676cecbef130004fbf400' }
PROVE IT
/Users/glenn/src/stampery-test/node_modules/stampery/dist/stampery.min.js:1
(function (exports, require, module, __filename, __dirname) { (function(){var a,b,c,d=function(a,b){return function(){return a.apply(b,arguments)}};b=require("crypto"),c=require("request"),a=function(){function a(a,c){var e;this.clientSecret=a,this.env=null!=c?c:"prod",this._merkleMix=d(this._merkleMix,this),this._checkSiblings=d(this._checkSiblings,this),this.prove=d(this.prove,this),this._req=d(this._req,this),this._post=d(this._post,this),this._get=d(this._get,this),this.stamp=d(this.stamp,this),this.getAll=d(this.getAll,this),this.getByHash=d(this.getByHash,this),this.getById=d(this.getById,this),this.clientId=b.createHash("md5").update(this.clientSecret).digest("hex").substring(0,15),e=new Buffer(this.clientId+":"+this.clientSecret),this.auth="Basic "+e.toString("base64"),this.host="beta"===this.env?"https://api-beta.stampery.com":"https://api-prod.stampery.com"}return a.prototype.hash=function(a){return b.createHash("sha256").

TypeError: a.equals is not a function
    at a._checkSiblings (/Users/glenn/src/stampery-test/node_modules/stampery/dist/stampery.min.js:1:2241)
    at a._checkSiblings (/Users/glenn/src/stampery-test/node_modules/stampery/dist/stampery.min.js:1:128)
    at a.prove (/Users/glenn/src/stampery-test/node_modules/stampery/dist/stampery.min.js:1:1986)
    at a.prove (/Users/glenn/src/stampery-test/node_modules/stampery/dist/stampery.min.js:1:128)
    at /Users/glenn/src/stampery-test/index2.js:33:48
    at /Users/glenn/src/stampery-test/node_modules/stampery/dist/stampery.min.js:1:1063
    at Request._callback (/Users/glenn/src/stampery-test/node_modules/stampery/dist/stampery.min.js:1:1816)
    at Request.self.callback (/Users/glenn/src/stampery-test/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
```

**Comment by aesedepece** [comment]
Basic tests have been added and they are passing!

[![Build Status](https://travis-ci.org/stampery/node.svg?branch=master)](https://travis-ci.org/stampery/node)

Acknowledgements to @grempe for pushing us towards better coding practices. :bowing_man:

**Comment by grempe** [comment]
There you go (`v6.0.2`)! Glad to see you fixed it and added some much needed tests. Best of luck to you.

```
$ node index2.js
RESPONSE stamp
{ hash: '4D15816D92CEE214F39D432D2E16BDC48191F70BA8A8DB57BF154C6A8E298AE8',
  id: '588802c9a637060004e29217',
  receipts: { eth: 25, btc: 430 },
  token: '1b997d902a3792e',
  time: '2017-01-25 01:43:37.447969' }
RESPONSE getById
{ hash: '4D15816D92CEE214F39D432D2E16BDC48191F70BA8A8DB57BF154C6A8E298AE8',
  id: '588802c9a637060004e29217',
  receipts:
   { eth:
      { proof: [],
        '@context': 'https://w3id.org/chainpoint/v2',
        merkleRoot: '4D15816D92CEE214F39D432D2E16BDC48191F70BA8A8DB57BF154C6A8E298AE8',
        type: 'BTA-SHA256',
        anchors: [Object],
        targetHash: '4D15816D92CEE214F39D432D2E16BDC48191F70BA8A8DB57BF154C6A8E298AE8' },
     btc: 394 },
  time: '2017-01-25 01:43:37.447000',
  token: '1b997d902a3792e' }
PROVE IT
Valid:  true
```
